### PR TITLE
frontend: upgrade angularjs 1.5 to 1.8

### PR DESCRIPTION
**Pull request by slaporte**

### CODE REVIEW

**Comment by mahmoud** [comment]
Oh nice! Well, short review, in any case, seems like. I guess my questions are:

1. Does this fix something in particular?
2. How did you determine to change the lines that you changed?
3. And maybe related to 2, what sort of testing did you do (and do you want me to do more?)

**Comment by slaporte** [comment]
Thanks for taking a look at it!

> Oh nice! Well, short review, in any case, seems like. I guess my questions are:
> 
> 1. Does this fix something in particular?

No, not really. I upgraded AngularJS by accident, then decided to see if I could get it working while it was in front of me. I think it resolves some of the dependencybot notices.

I also noticed that angular 1.8 is [getting pretty old](https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c), and won't get updates after next year.

> 2. How did you determine to change the lines that you changed?

I just compiled it locally and fixed errors as I encountered them.

> 3. And maybe related to 2, what sort of testing did you do (and do you want me to do more?)

Do you know if there's a better way to test? It's working fine for me, but I put this in a pull request because I wasn't super confident how to test it out.

**Comment by mahmoud** [comment]
Got it. Yeah, for the frontend, I'm not aware of a better strategy than clicking around at the moment. Can I ask, how much clicking around did you do?

**Review by mahmoud — APPROVED** [review]
I'm +1 to this. I was able to build locally and run from scratch on this branch. Clicking around seems to be fine, as well.

**Comment by mahmoud** [comment]
Thread seems to have settled, so I've merged :) Great work!

**Pull request merged**
