### PR TITLE
Refactor and clean up admin tools

### PR DESCRIPTION
**Pull request by mahmoud**
Using the master branch of face, massively cleaned up the admin tools. I think there's still a little ways to go to create a full-blown CLI, but figured I'd open up a PR to start reviewing, as the changes are pretty sizable.

### CODE REVIEW

**Comment by mahmoud** [comment]
The new interface is subcommand-driven instead of flags, and has a much nicer help:

```$ python tools/admin.py -h
Usage: tools/admin.py subcommand [FLAGS]

CLI tools for administrating Montage.


Subcommands:

  add-organizer               Add a top-level organizer to the system, capable of creating campaigns and adding
                              coordinators.
  add-coordinator             add specified user as coordinator of a given campaign
  create-campaign             interactively create a campaign
  cancel-campaign             cancel the specified campaign
  create-round                interactively create a round in the specified campaign
  import-gist                 import round entries from a csv list
  activate-round              activate a round to start or resume voting
  pause-round                 pause a round to make edits and perform other maintenance
  advance-round               finalize the specified round and start the next
  edit-round-quorum           change the quorum of a given round, assigning and reassigning tasks as need be
  check-round-dupes           check for double-assigned tasks or ratings in a specified round
  apply-round-ratings         apply ratings to a round based on an input file
  retask-duplicate-ratings    reassign all ratings that were duplicated
  shuffle-round-assignments   randomly reassign all the rating tasks in a round
  cancel-round                set a round as cancelled, cancel related tasks and remove it from the campaign's active
                              rounds.
  list-campaigns              list details about all campaigns
  rdb-console                 Load a developer console for interacting with database objects.


Flags:

  --help / -h   show this help message and exit```

And the help of a subcommand:

```
$ python tools/admin.py cancel-campaign -h
Usage: tools/admin.py cancel_campaign [FLAGS]

cancel the specified campaign


Flags:

  --help / -h                 show this help message and exit
  --debug                     get extra output, enable debug console before db commit
  --force                     skip some confirmations, use with caution
  --campaign-id CAMPAIGN_ID   integer (required)
```

**Comment by slaporte** [comment]
This format is a big improvement. I personally like the proposal for more hierarchy, like `montage-cli round activate`.

Does each subcommand specify which flags are relevant/required? (eg, some need campaign-id, others need round-id, you'd never need both)

**Comment by mahmoud** [comment]
Yep! face does that automatically :)

**Comment by mahmoud** [comment]
Alright, calling this good for now. The rest we'll fix forward. The priority right now is to get this into a real packaged state, with admin tools living inside the montage app. Then we refactor the tests, get the CLI under test, and maybe do some instrumenting.

**Pull request merged**
